In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("application_test.csv")

In [5]:
#顯示前五筆資料
df.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#數據的資料
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 121 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(40), object(16)
memory usage: 45.0+ MB

In [35]:
#列出資料的大小 (In[4], Hint : shape)

alldata=df.shape
colums=df.shape[1]
rows=df.shape[0]

print(alldata)
print("This data have %d colums" % (colums))
print("This data have %d rows" % (rows))

(48744, 121)
This data have 121 colums
This data have 48744 rows

In [73]:
#列出所有欄位 (In[5], 有多種寫法)
pd.set_option('display.max_columns',None)
df

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.018850,-19241,-2329,-5170.0,-812,NaN,1,1,0,1,0,1,NaN,2.0,2,2,TUESDAY,18,0,0,0,0,0,0,Kindergarten,0.752614,0.789654,0.159520,0.0660,0.0590,0.9732,NaN,NaN,NaN,0.1379,0.1250,NaN,NaN,NaN,0.0505,NaN,NaN,0.0672,0.0612,0.9732,NaN,NaN,NaN,0.1379,0.1250,NaN,NaN,NaN,0.0526,NaN,NaN,0.0666,0.0590,0.9732,NaN,NaN,NaN,0.1379,0.1250,NaN,NaN,NaN,0.0514,NaN,NaN,NaN,block of flats,0.0392,"Stone, brick",No,0.0,0.0,0.0,0.0,-1740.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.035792,-18064,-4469,-9118.0,-1623,NaN,1,1,0,1,0,0,Low-skill Laborers,2.0,2,2,FRIDAY,9,0,0,0,0,0,0,Self-employed,0.564990,0.291656,0.432962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,NaN,Working,Higher education,Married,House / apartment,0.019101,-20038,-4458,-2175.0,-3503,5.0,1,1,0,1,0,0,Drivers,2.0,2,2,MONDAY,14,0,0,0,0,0,0,Transport: type 3,NaN,0.699787,0.610991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-856.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.026392,-13976,-1866,-2000.0,-4208,NaN,1,1,0,1,1,0,Sales staff,4.0,2,2,WEDNESDAY,11,0,0,0,0,0,0,Business Entity Type 3,0.525734,0.509677,0.612704,0.3052,0.1974,0.9970,0.9592,0.1165,0.3200,0.2759,0.3750,0.0417,0.2042,0.2404,0.3673,0.0386,0.0800,0.3109,0.2049,0.9970,0.9608,0.1176,0.3222,0.2759,0.3750,0.0417,0.2089,0.2626,0.3827,0.0389,0.0847,0.3081,0.1974,0.9970,0.9597,0.1173,0.32,0.2759,0.3750,0.0417,0.2078,0.2446,0.3739,0.0388,0.0817,reg oper account,block of flats,0.3700,Panel,No,0.0,0.0,0.0,0.0,-1805.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010032,-13040,-2191,-4000.0,-4262,16.0,1,1,1,1,0,0,NaN,3.0,2,2,FRIDAY,5,0,0,0,0,1,1,Business Entity Type 3,0.202145,0.425687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-821.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,100042,Cash loans,F,Y,Y,0,270000.0,959688.0,34600.5,810000.0,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,0.025164,-18604,-12009,-6116.0,-2027,10.0,1,1,0,1,1,0,Drivers,2.0,2,2,MONDAY,15,0,0,0,0,0,0,Government,NaN,0.628904,0.392774,0.2412,0.0084,0.9821,0.7552,0.0452,0.1600,0.1379,0.3333,0.3750,0.1683,0.1942,0.2218,0.0116,0.0731,0.2458,0.0088,0.9821,0.7648,0.0457,0.1611,0.1379,0.3333,0.3750,0.1721,0.2121,0.2311,0.0117,0.0774,0.2436,0.0084,0.9821,0.7585,0.0455,0.16,0.1379,0.3333,0.3750,0.1712,0.1975,0.2258,0.0116,0.0746,not specified,block of flats,0.2151,Block,No,0.0,0.0,0.0,0.0,-1705.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
6,100057,Cash loans,M,Y,Y,2,180000.0,499221.0,22117.5,373500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.022800,-16685,-2580,-10125.0,-241,3.0,1,1,0,1,0,0,High skill tech staff,4.0,2,2,THURSDAY,9,0,0,0,0,1,1,Industry: type 9,0.760851,0.571084,0.651260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-1182.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
7,100065,Cash loans,M,N,Y,0,166500.0,180000.0,14220.0,180000.0,Unaccompanied,Working,Higher education,Single / not married,With parents,0.005144,-9516,-1387,-5063.0,-2055,NaN,1,1,1,1,1,0,Core staff,1.0,2,2,FRIDAY,7,0,0,0,0,0,0,Self-employed,0.565290,0.613033,0.312365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1182.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
8,100066,Cash loans,F,N,Y,0,315000.0,364896.0,28957.5,315000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.046220,-12744,-1013,-1686.0,-3171,NaN,1,1,0,1,0,0,Core staff,2.0,1,1,THURSDAY,18,0,0,0,0,0,0,School,0.718507,0.808788,0.522697,0.1031,0.1115,0.9781,NaN,NaN,0.0000,0.2069,0.1667,NaN,NaN,NaN,NaN,NaN,NaN,0.1050,0.1157,0.9782,NaN,NaN,0.0000,0.2069,0.1667,NaN,NaN,NaN,NaN,NaN,NaN,0.1041,0.1115,0.9781,NaN,NaN,0.00,0.2069,0.1667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,block of flats,0.0702,"Stone, brick",No,0.0,0.0,0.0,0.0,-829.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
9,100067,Cash loans,F,Y,Y,1,162000.0,45000.0,5337.0,45000.0,Family,Working,Higher education,Civil marriage,House / apartment,0.018634,-10395,-2625,-8124.0,-3041,5.0,1,1,1,1,1,0,Sales staff,3.0,2,2,TUESDAY,14,0,0,0,0,0,0,Trade: type 2,0.210562,0.444848,0.194068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.0,4.0,0.0,-1423.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
10,100074,Cash loans,F,N,Y,0,67500.0,675000.0,25447.5,675000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.003122,-23670,365243,-7490.0,-4136,NaN,1,0,0,1,1,0,NaN,2.0,3,3,TUESDAY,11,0,0,0,0,0,0,XNA,NaN,0.660015,0.298595,0.0216,0.0545,0.9781,NaN,NaN,0.0000,0.1034,0.0417,NaN,0.0095,NaN,0.0113,NaN,NaN,0.0221,0.0566,0.9782,NaN,NaN,0.0000,0.1034,0.0417,NaN,0.0097,NaN,0.0117,NaN,NaN,0.0219,0.0545,0.9781,NaN,NaN,0.00,0.1034,0.0417,NaN,0.0096,NaN,0.0115,NaN,NaN,NaN,block of flats,0.0136,"Stone, brick",No,0.0,0.0,0.0,0.0,-1671.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
11,100090,Cash loans,F,N,Y,0,135000.0,261621.0,16848.0,216000.0,Unaccompanied,Working,Secondary / secondary special,Widow,House / apartment,0.008019,-15524,-3555,-7833.0,-3985,NaN,1,1,0,1,0,0,Laborers,1.0,2,2,FRIDAY,17,0,0,0,0,1,1,Self-employed,0.756722,0.393715,0.436506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1097.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
12,100091,Cash loans,F,N,Y,0,247500.0,296280.0,23539.5,225000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.018634,-12278,-929,-6031.0,-4586,NaN,1,1,0,1,0,0,NaN,2.0,2,2,THURSDAY,17,0,0,0,0,0,0,Self-employed,0.263238,0.470036,0.415347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,-619.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
13,100092,Cash loans,F,Y,Y,0,90000.0,360000.0,18535.5,360000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.014520,-19687,-3578,-10673.0,-3183,3.0,1,1,0,1,0,0,Core staff,2.0,2,2,TUESDAY,7,0,0,0,0,1,1,Government,0.304940,0.270255,0.375711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0.0,5.0,0.0,-1414.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
14,100106,Revolving loans,M,N,Y,0,180000.0,157500.0,7875.0,157500.0,"Spouse, partner",Working,Secondary / secondary special,Civil marriage,House / apartment,0.031329,-12091,-1830,-1042.0,-4221,NaN,1,1,0,0,0,0,Laborers,2.0,2,2,TUESDAY,9,0,0,0,1,1,0,Business Entity Type 3,NaN,0.485770,0.579727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-765.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
15,100107,Cash loans,M,Y,Y,0,180000.0,296280.0,21690.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.032561,-13563,-1007,-5719.0,-4044,14.0,1,1,0,1,0,1,Laborers,2.0,1,1,TUESDAY,15,0,0,0,0,0,0,Business Entity Type 3,0.344165,0.684407,0.263647,0.0371,0.0361,0.9513,0.3336,0.0132,0.0000,0.1379,0.1250,0.1667,0.0320,0.0286,0.0613,0.0077,0.0007,0.0378,0.0375,0.9513,0.3597,0.0134,0.0000,0.1379,0.1250,0.1667,0.0327,0.0312,0.0639,0.0078,0.0008,0.0375,0.0361,0.9513,0.3425,0.0133,0.00,0.1379,0.1250,0.1667,0.0326,0.0291,0.0624,0.0078,0.0007,reg oper account,block of flats,0.0484,"Stone, brick",No,2.0,0.0,2.0,0.0,-317.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
16,100109,Cash loans,F,Y,Y,0,202500.0,407520.0,26041.5,360000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.007020,-19375,-4739,-3035.0,-2895,11.0,1,1,1,1,0,0,Laborers,1.0,2,2,SATURDAY,15,0,0,0,0,0,0,Services,0.583118,0.635028,0.306202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2154.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
17,100117,Cash loans,M,Y,Y,0,90000.0,499221.0,22117.5,373500.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.003122,-22705,365243,-5107.0,-5990,15.0,1,0,0,1,0,0,NaN,2.0,3,3,FRIDAY,10,0,0,0,0,0,0,XNA,0.587175,0.646764,0.652897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1132.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
18,100128,Cash loans,F,Y,Y,1,225000.0,431280.0,23526.0,360000.0,Unaccompanied,Commercial associate,Higher education,Civil marriage,With parents,0.025164,-10962,-1883,-99.0,-1721,8.0,1,1,0,1,0,1,Managers,3.0,2,2,THURSDAY,10,0,0,0,0,0,0,Bank,0.339002,0.375073,0.347418,0.1093,0.0464,0.9881,0.8368,0.0000,0.1200,0.1034,0.3750,0.4167,0.0000,0.0891,0.0986,0.0000,0.0282,0.1113,0.0482,0.9881,0.8432,0.0000,0.1208,0.1034,0.3750,0.4167,0.0000,0.0973,0.1027,0.0000,0.0299,0.1103,0.0464,0.9881,0.8390,0.0000,0.12,0.1034,0.3750,0.4167,0.0000,0.0906,0.1004,0.0000,0.0288,reg oper account,block of flats,0.0837,Panel,No,5.0,0.0,5.0,0.0,-1616.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,3.0,4.0
19,100141,Cash loans,F,Y,Y,0,175500.0,478498.5,46741.5,454500.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.010147,-17955,-305,-10087.0,-1516,10.0,1,1,1,1,0,0,Laborers,2.0,2,2,TUESDAY,11,1,1,0,1,1,0,Industry: type 3,0.696566,0.742765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-814.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
20,100150,Cash loans,F,N,Y,0,99000.0,225000.0,19242.0,225000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Civil marriage,House / apartment,0.007274,-10507,-2780,-5072.0,-2729,NaN,1,1,0,1,1,0,Sales staff,2.0,2,2,TUESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.590531,0.600999,0.761026,0.0825,0.0654,0.9762,0.6736,0.0000,0.0000,0.1379,0.1667,0.2083,0.0477,0.0672,0.0474,0.0000,0.0000,0.0840,0.0678,0.9762,0.6864,0.0000,0.0000,0.1379,0.1667,0.2083,0.0488,0.0735,0.0494,0.0000,0.0000,0.0833,0.0654,0.9762,0.6780,0.0000,0.00,0.1379,0.1667,0.2083,0.0486,0.0684,0.0482,0.0000,0.0000,reg oper account,block of flats,0.0547,Panel,No,0.0,0.0,0.0,0.0,-2297.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
21,100168,Cash loans,F,N,Y,0,157500.0,266652.0,16443.0,202500.0,Unaccompanied,Working,Higher education,Widow,House / apartment,0.011657,-22557,-13294,-13154.0,-4187,NaN,1,1,0,1,0,0,NaN,1.0,1,1,TUESDAY,15,0,0,0,0,0,0,Other,NaN,0.708939,0.746300,0.0515,0.0455,0.9627,NaN,NaN,0.0400,0.1379,0.2083,NaN,0.0000,NaN,0.0000,NaN,0.0397,0.0525,0.0472,0.9628,NaN,NaN,0.0403,0.1379,0.2083,NaN,0.0000,NaN,0.0000,NaN,0.0421,0.0520,0.0455,0.9627,NaN,NaN,0.04,0.1379,0.2083,NaN,0.0000,NaN,0.0000,NaN,0.0406,NaN,block of flats,0.0508,"Stone, brick",No,0.0,0.0,0.0,0.0,-1144.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
22,100169,Cash loans,F,N,Y,0,135000.0,540000.0,27702.0,540000.0,Family,Pensioner,Higher education,Separated,House / apartment,0.072508,-22784,365243,-5103.0,-5229,NaN,1,0,0,1,0,0,NaN,1.0,1,1,TUESDAY,12,0,0,0,0,0,0,XNA,0.866010,0.638614,0.159520,0.3423,0.1420,0.9925,0.8980,0.0000,0.4000,0.1724,0.6667,0.7083,0.0000,0.2749,0.3755,0.0193,0.0164,0.3487,0.1474,0.9926,0.9020,0.0000,0.4028,0.1724,0.6667,0.7083,0.0000,0.3003,0.3912,0.0195,0.0174,0.3456,0.1420,0.9925,0.8994,0.0000,0.40,0.1724,0.6667,0.7083,0.0000,0.2796,0.3822,0.0194,0.0167,reg oper account,block of flats,0.2989,Panel,No,0.0,0.0,0.0,0.0,-519.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
23,100170,Cash loans,M,N,Y,1,337500.0,1313212.5,42493.5,1012500.0,Unaccompanied,Commercial associate,Incomplete higher,Married,House / apartment,0.024610,-11948,-1415,-5611.0,-4052,NaN,1,1,0,1,0,1,Laborers,3.0,2,2,TUESDAY,11,0,0,0,0,0,0,Business Entity Type 3,NaN,0.661226,0.440058,0.1237,0.0595,0.9866,NaN,NaN,0.1200,0.1034,0.3750,NaN,0.0629,NaN,0.1239,NaN,0.0243,0.1261,0.0617,0.9866,NaN,NaN,0.1208,0.1034,0.3750,NaN,0.0644,NaN,0.1291,NaN,0.0257,0.1249,0.0595,0.9866,NaN,NaN,0.12,0.1034,0.3750,NaN,0.0640,NaN,0.1261,NaN,0.0248,NaN,block of flats,0.1217,Panel,No,1.0,0.0,1.0,0.0,-1582.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
24,100171,Cash loans,M,Y,Y,0,157500.0,539100.0,29245.5,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.031329,-13172,-3518,-6207.0,-4243,20.0,1,1,1,1,0,0,Drivers,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,Business Entity Type 3,NaN,0.687408,0.662638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0.0,7.0,0.0,-2470.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
25,100172,Cash loans,F,N,Y,0,76500.0,225000.0,12334.5,225000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.010966,-15394,-967,-5389.0,-5433,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,TUESDAY,10,0,0,0,0,1,1,Business Entity Type 3,NaN,0.348886,0.535276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,4.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
26,100184,Cash loans,F,N,Y,0,112500.0,256032.0,10759.5,180000.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.019689,-21150,365243,-4157.0,-4658,NaN,1,0,0,1,0,0,NaN,1.0,2,2,THURSDAY,11,0,0,0,0,0,0,XNA,NaN,0.263101,0.474051,0.1361,NaN,0.9826,0.7620,0.0573,0.0000,0.0690,0.1667,0.2083,0.0645,NaN,0.0488,NaN,0.0284,0.1387,NaN,0.9826,0.7713,0.0579,0.0000,0.0690,0.1667,0.2083,0.0660,NaN,0.0509,NaN,0.0301,0.1374,NaN,0.9826,0.7652,0.0577,0.00,0.0690,0.1667,0.2083,0.0656,NaN,0.0497,NaN,0.0290,reg oper account,block of flats,0.0759,"Stone, brick",No,1.0,0.0,1.0,0.0,-672.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
27,100187,Cash loans,F,N,Y,0,225000.0,501363.0,25726.5,418500.0,Family,Commercial associate,Higher education,Married,House / apartment,0.031329,-21040,-2467,-918.0,-3663,NaN,1,1,0,1,1,0,NaN,2.0,2,2,THURSDAY,12,0,0,0,0,0,0,Self-employed,NaN,0.266212,0.595456,0.0722,NaN,0.9965,NaN,NaN,0.0400,0.0345,0.5000,NaN,NaN,NaN,0.0986,NaN,0.0843,0.0735,NaN,0.9965,NaN,NaN,0.0403,0.0345,0.5000,NaN,NaN,NaN,0.1027,NaN,0.0893,0.0729,NaN,0.9965,NaN,NaN,0.04,0.0345,0.5000,NaN,NaN,NaN,0.1004,NaN,0.0861,NaN,block of flats,0.1175,"Stone, brick",No,5.0,1.0,5.0,1.0,-1792.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100212,Cash loans,F,Y,N,0,90000.0,450000.0,23107.5,450000.0,Unaccompanied,Working,Lower secondary,Married,House / apartment,0.005002,-15773,-1310,-7173.0,-5049,22.0,1,1,0,1,0,0,Core staff,2.0,3,3,MONDAY,15,0,0,0,0,0,0,Self-employed,NaN,0.762953,0.357293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0.0,5.0,0.0,-2865.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [93]:
#擷取部分資料 (In[6], Hint : loc 或 iloc)
df[['FLAG_OWN_REALTY','CNT_CHILDREN','AMT_INCOME_TOTAL']][0:5]

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL
0               Y             0          135000.0
1               Y             0           99000.0
2               Y             0          202500.0
3               Y             2          315000.0
4               N             1          180000.0

In [92]:
#擷取部分資料 (In[6], Hint : loc 或 iloc)
#利用iloc取每一列的第0跟1行
X = df.iloc[:, [0, 1]].values
X

array([[100001, 'Cash loans'],
       [100005, 'Cash loans'],
       [100013, 'Cash loans'],
       ...,
       [456223, 'Cash loans'],
       [456224, 'Cash loans'],
       [456250, 'Cash loans']], dtype=object)